# Generated by Django 4.0.2 on 2022-05-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=54, verbose_name='email')),
                ('feed', models.TextField(max_length=250, verbose_name='feedback')),
                ('stars', models.IntegerField(default=0, verbose_name='star')),
                ('for_lawyer', models.CharField(default=' ', max_length=250, verbose_name='for_lawyer')),
            ],
        ),
    ]
